### ISSUE TITLE
given pacts dir not used

### ISSUE THREAD

**Issue by ireinhart** [pact-foundation/pact-mock_service#111]
Hello,

I have a strange behavior and could not say anything other than "not working".

If I start the service with
     pact-mock-service start --pact-dir=build/test/pact

the pacts are written to ./pacts and not ./build/test/pact/pacts

How can I debug that? How can I change the directory of written pacts?

All other options like --pid-dir and -l working.

Best,
Ingo

**Comment by bethesque** [comment]
Looks like the dir is not being passed through to something. Can you reproduce it with https://github.com/pact-foundation/pact-ruby-standalone-e2e-example please?

**Comment by ireinhart** [comment]
Thanks for your support. I try your issue repo and found a solution for my problem.

We are using a library that set the pact_dir value on every request. That seams to overwrite the server settings. *pact_dir* is an interesting option - in my point of view ;-)

I update the library and now it works like expected.

You can look into it:
https://github.com/chefkoch-dev/pact_consumer_dart/commit/a16193325cca88998ff7b35d2b7345f8b2663959#diff-0cacca8d4f91b310f265ea85f6b69e18L39
