### ISSUE TITLE
Ruby 2.7 cannot load such file -- thwait

### ISSUE THREAD

**Issue by mtchavez** [pact-foundation/pact-mock_service#115]
|Info                     | Value
-----------------|------
**gem version** | 3.2.0
**ruby version** | 2.7.0

## What

Ruby 2.7 has removed several standard library components and replaced them with gems. One of those is `thwait` which is being used in this gem.

## Suggested Fix

- Install [thwait gem][thwait] if the ruby version does not have it in the standard library

## Notes

- [Ruby 2.7 release notes][release-notes] has the following
  
    ```
    The following libraries are no longer bundled gems. Install corresponding gems to use these features.

    CMath (cmath gem)
    Scanf (scanf gem)
    Shell (shell gem)
    Synchronizer (sync gem)
    ThreadsWait (thwait gem)
    E2MM (e2mmap gem)
    ```

[release-notes]: https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
[thwait]: https://github.com/ruby/thwait

**Comment by maneframe** [comment]
Does `thwait` still need to be required at all? I don't see any obvious references to `ThreadsWait` anywhere...

**Comment by mtchavez** [comment]
Very good point. Now that you bring it up, I searched the git history and it appears to have been cargo-culted and _just worked ™_ because it was bundled with Ruby before `2.7`. Can a maintainer confirm this is the case and we can remove it entirely? Good catch @maneframe

**Comment by bethesque** [comment]
Have you got a link to a build with the actual error?

**Comment by mtchavez** [comment]
I am not clear how you want people to contribute these sorts of things so I made a pull request #116 adding 2.7 to the build matrix to show the failure. It is really just using 2.7 and running the tests as the pull request description suggests. Failure: https://travis-ci.org/pact-foundation/pact-mock_service/jobs/635004086

**Comment by bethesque** [comment]
What happens if you remove the `require 'thwait'` line?

**Comment by mtchavez** [comment]
I would love to do something like that if the dependency isn't needed. Just need a maintainer to make a decision on that.

**Comment by bethesque** [comment]
The pact-mock_service maintainer? That's me. I've just deleted the require locally, and it doesn't cause any immediately apparent errors, but I'm not sure if that particular piece of code has a test in this code base. The mock service code was pulled out of a single "monolith" pact gem years ago, so the tests that execute it might actually be in the pact gem, because it's only the Pact gem that uses the AppManager.

When I remove the thwait require, I then get a heap of keyword argument errors for webmock.

**Comment by bethesque** [comment]
Not that the thwait gem has anything to do with it - just saying, there's a next level of errors after the thwait issue!

**Comment by bethesque** [comment]
I've deleted the require, it all seems to work ok.
