### ISSUE TITLE
Can you please provide me the response model for POST /pact endpoint.

### ISSUE THREAD

**Issue by Morshed11218** [pact-foundation/pact-mock_service#139]
Hi,
Not an issue. 

I'm trying to do some custom things with the response from POST /pact endpoint. I need to deserialize the response model. I tried looking through the repo but unable to find it. Sorry I'm not familiar with ruby code. Thanks.

**Comment by bethesque** [comment]
Can you describe the underlying problem you're trying to solve.

**Comment by Morshed11218** [comment]
I'm trying to remove a specific interaction from the (Post /pact) response and then perform (PUT /interaction) request to update it which will remove the interaction. Looks like I'm able to do this without the model. So I no longer need this. Closing request. Thanks
