### ISSUE TITLE
Running with Rack > 3.1 gives error `uninitialized constant Rack::Handler`

### ISSUE THREAD

**Issue by pezholio** [pact-foundation/pact-mock_service#151]
# Pre issue-raising checklist

I have already:

* [x] Read through the relevant docs at https://docs.pact.io
* [x] Upgraded to the latest version of the gem
* [x] Checked the CHANGELOG to see if the issue I am about to raise has been fixed
* [x] Created an executable example that demonstrates the issue using either a:
  * Dockerfile
  * Git repository with a Travis or Appveyor (or similar) build

## Software versions

* **OS**: Mac OSX 14.5
* **pact mock service:** v 3.12.1

## Expected behaviour

Tests pass

## Actual behaviour

When running the tests with Rack version >= 3.1.0, the tests fail with the error:

```
NameError:
    uninitialized constant Rack::Handler
```

This looks related to changes in Rack starting 3.1.0 - https://github.com/rack/rack/blob/main/CHANGELOG.md#310---2024-06-11

## Steps to reproduce

An example build with Rack > 3.1.0 ❌ 

https://github.com/alphagov/pact-mock_service/actions/runs/9513302857

And example build with Rack < 3.1.0 ✅ 

https://github.com/alphagov/pact-mock_service/actions/runs/9513330459

**Comment by Harriethw** [comment]
I've put a fix that worked for me locally here https://github.com/pact-foundation/pact-mock_service/pull/146/files#r1639534752
