### ISSUE TITLE
Non-HTTP service

### ISSUE THREAD

**Issue by mkozjak** [pact-foundation/pact-mock_service#58]
Are there any plans to add a possibility to use services that are not HTTP (ie. REST API) based?

I'm currently looking into adding messaging support to [pact-js](https://github.com/pact-foundation/pact-js) which ultimately uses pact-mock_service.

The most neat way for this would be to implement a service for message broker mocks here (RabbitMQ, NATS, Kafka...).

**Comment by bethesque** [comment]
@uglyog what's the go with the messaging pact spec? Is it a thing yet?

I don't have any plans to create the messaging mock service myself, but very happy to support someone else in doing it.

**Comment by uglyog** [comment]
It's a thing: https://github.com/pact-foundation/pact-specification/tree/version-3#introduces-messages-for-services-that-communicate-via-event-streams-and-message-queues

I use it to test contracts between lambda functions and applications.

**Comment by YOU54F** [comment]
pact-message-ruby gems offers async message contracts, in v3 spec with some caveats

https://github.com/pact-foundation/pact-message-ruby

There is a fully featured version built in rust, available standalone as a CLI

https://github.com/pact-foundation/pact-core-mock-server

or available as a ffi library and available in multiple languages that support interop

Example here which I am building out

https://github.com/YOU54F/pact-ruby-ffi

This mock service as a standalone cli is likely to be deprecated as its functionality wont be required with the ffi interop (which provides a mock service itself)
