### ISSUE TITLE
Add bash examples to repository

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-mock_service#69]
Copy from:
https://gist.github.com/bethesque/9d81f21d6f77650811f4

**Comment by YOU54F** [comment]
I believe this is partially done

we have the single interaction example from the gist, albeit with minor changes.

https://github.com/pact-foundation/pact-mock_service/tree/master/script

so just wants these two example types moving across

- [3-multiple-interactions-at-same-time.sh](https://gist.github.com/bethesque/9d81f21d6f77650811f4#file-3-multiple-interactions-at-same-time-sh)
- [3-multiple-interactions.sh](https://gist.github.com/bethesque/9d81f21d6f77650811f4#file-3-multiple-interactions-sh)

**Comment by bethesque** [comment]
I'm not really sure why I wanted those. Maybe it was to show wrapper library implementers how to use the mock service. I think we should just close this.
