### ISSUE TITLE
Since new Update my pact-mock does not work anymore.

### ISSUE THREAD

**Issue by Pingudiem** [pact-foundation/pact-mock_service#85]
I am testing an interface and use pact to get my descirption up to pact-broker.

My interface is working as planned with the now existing service, but my pact-mock is not working anymore. 

Since the last updates I get the following error. I was guessing it had to do with the new zone.js update but I have read that it should no longer be an issue.

`TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:106:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:106:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:104:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>
        TypeError: Cannot read property 'run' of null
            at <Jasmine>
            at UserContext.<anonymous> node_modules/zone.js/dist/jasmine-patch.js:104:1)
            at <Jasmine>
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask node_modules/zone.js/dist/zone.js:421:1)
            at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask node_modules/zone.js/dist/zone.js:188:1)
            at drainMicroTaskQueue node_modules/zone.js/dist/zone.js:595:1)
            at <Jasmine>`

 

> "dependencies": {
>     "@angular/animations": "^5.2.3",
>     "@angular/common": "^5.2.3",
>     "@angular/compiler": "^5.2.3",
>     "@angular/core": "^5.2.3",
>     "@angular/forms": "^5.2.3",
>     "@angular/http": "^5.2.3",
>     "@angular/platform-browser": "^5.2.3",
>     "@angular/platform-browser-dynamic": "^5.2.3",
>     "@angular/router": "^5.2.3",
>     "core-js": "^2.4.1",
>     "jasmine": "^3.0.0",
>     "ncu": "^0.2.1",
>     "rxjs": "^5.5.6",
>     "zone": "^0.3.4",
>     "zone.js": "^0.8.19"
>   },
>   "devDependencies": {
>     "@angular/cli": "^1.7.1",
>     "@angular/compiler-cli": "^5.2.6",
>     "@angular/language-service": "^5.2.6",
>     "@pact-foundation/karma-pact": "2.1.5",
>     "@pact-foundation/pact-node": "6.10.0",
>     "@pact-foundation/pact-web": "5.6.1",
>     "@types/jasmine": "^2.8.6",
>     "@types/jasminewd2": "~2.0.2",
>     "@types/node": "~9.4.1",
>     "codelyzer": "^4.0.1",
>     "cross-env": "^5.0.5",
>     "jasmine-core": "~3.0.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "^2.0.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^1.2.1",
>     "karma-jasmine": "~1.1.0",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "protractor": "~5.3.0",
>     "ts-node": "~5.0.0",
>     "tslint": "^5.9.1",
>     "typescript": "^2.7.2"
>   }
> }

Is that still an Zone issue or is it on your side?

thank you!

**Comment by bethesque** [comment]
This is a problem in the JavaScript wrapper code, so can you raise this in pact-js please?
