### ISSUE TITLE
Work out why the mock service takes 12-14 seconds to start up

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-mock_service#96]
See https://github.com/pact-foundation/pact-php/pull/90

**Comment by frastel** [comment]
My setup is a bit more complex. I do not start the pact-mock-service on my bare machine.
Im running a container within a vagrant box. The mock service is started with the help of pact-foundation/pact-php.
I try to push my environment setup somewhere for better reproduction.

**Comment by bethesque** [comment]
Oh, ok. I don't feel guilty about that! Is there anything we could do help this situation apart from extending the timeout?

**Comment by frastel** [comment]
No problem and I am totally fine with the extension of the timeout.
In former times we started the containerized mock service by hand before we executed the test suites. This startup was more complex and took even longer.
Using the mock service wrapper is an improvement for us and thus I really see no need for any improvement on your side.

**Comment by bethesque** [comment]
Ok, all good then!
