### ISSUE TITLE
Unable to set response body to "falsey" values

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-mock_service#99]
Setting the response body directly to a `null` or `false` value results in an empty response from the mock server.

How to reproduce:

```sh
bundle exec bin/pact-mock-service service \
  --port 1234 \
  --consumer Foo \
  --provider Bar \
  --pact-specification-version 2 \
  --pact-dir ./tmp/pacts \
  --log ./tmp/bar_mock_service.log \
  --log-level DEBUG &
pid=$!

# Wait a few seconds, then register the interaction:

curl -X POST -H "X-Pact-Mock-Service: true"  localhost:1234/interactions -d '{
  "description": "foo",
  "request": {
    "path": "/foo",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "body": null
  }
}'

# Test the response
curl localhost:1234/foo

```

I believe the `render_body` method is to blame, specifically [this line](https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/mock_service/request_handlers/interaction_replay.rb#L181) which checks for a falsey value of the body, meaning if the body is `nil` or `false` it returns an empty string.

I couldn't glean from the tests the exact behaviour as to why this statement existed in the first place, but my suspicion is that we need to be able to deal with the 'body not present' case to avoid returning `null`. However, this is presenting the explicit `null` / `false` case.

FWIW removing that line didn't cause in test failures, so perhaps we need to get some coverage on it.

See https://github.com/pact-foundation/pact-js/issues/257 for background.

**Comment by bethesque** [comment]
This is tricky. What are you expecting the HTTP request to look like? `null` or `false`? How would you differentiate it from an empty body?

**Comment by mefellows** [comment]
> This is tricky.

Indeed!

In this case, the body is a _literal_ `false`. I think it could be differentiated because it would have the header `Content-Length: 5`. At least, that is the only way i can think of separating them.

**Comment by NiklasEi** [comment]
Any updates here? This issue makes it impossible to write pact tests for endpoints returning only a boolean.

**Comment by bethesque** [comment]
I've changed it to `return '' if body.nil?` and released the mock service. I have not done any testing on it. You'll need to get the pact client of whichever language you're using updated to the latest pact-ruby-standalone.

**Comment by mefellows** [comment]
Thanks Beth.

@NiklasEi what language are you using that needs it?

**Comment by NiklasEi** [comment]
Thanks for the update!

> @NiklasEi what language are you using that needs it?

Javascript

**Comment by mefellows** [comment]
Yep, will get a new release out this week. Thanks
